Fix reverse dependencies output in `eopkg info` with local repo present
getsolus/package-management pull request #17
Opened 2023-04-23 08:30 UTC by liontiger23

`eopkg info` used reverse dependencies from the first repo available instead of the one, where the package was actually found. This caused it to show less reverse dependencies if you have local repository set up as the first repo in `eopkg`.

2023-04-23 09:21 UTC, ermo requested changes
I would encourage you to add relevant output in a "before <-> after" sense to show that this patch does what it says on the tin:

Before:
```
eopkg (...)
(...)
```

After
```
eopkg (...)
(...)
```

Thanks in advance.

2023-04-23 10:11 UTC, liontiger23 commented
Updated commit-message and description with reproduction steps.

2023-04-23 15:26 UTC, ermo reviewed
This commit message is much better than before.

1. Does the repo order need to ALWAYS have the local repo listed first?
2. IFF 1. is true, THEN  where should this be documented?

Would it in fact be _better_ for eopkg to be able to recognise local repos (= non https:// or some similar heuristic) and _always_ ensure that they are configured first? Otherwise this is only a fix if the user _knows_ that local repos should be listed first?

But IF it's an eopkg implementation detail (like in the present PR), then shouldn't it be the responsibility of eopkg to ensure that if a local repo is indeed present, then it is automagically set up correctly too?

2023-04-23 16:01 UTC, liontiger23 commented
In my opinion, this patch fixes a general problem, that reverse dependencies are calculated for the correct repo (the one for which corresponding output is printed), regardless of the nature of that repo.

The first repo might as well be https repo, but with different set of packages. With local repo it is just easier to reproduce, since this was the scenario where we first encountered this issue.

2023-04-23 16:07 UTC, liontiger23 commented
As for the details in precedence of repos, I think it is somewhat documented in the https://github.com/getsolus/help-center-docs/blob/master/packaging/local-repository/en.md#best-practices-when-working-with-a-solbuild-local-repository

But I am not quite sure, if this is what you mean.

I am not really familiar with the general eopkg design and full intended functionality.

2023-04-23 17:44 UTC, ermo commented
Please reference [this discussion](https://matrix.to/#/!tyWxyaiMNivbIImvvh:matrix.org/$_tJOcr_rvInNKeEpYy7nTEthKpI7JD5Vf6O-tWloxyg?via=matrix.org&via=kde.org&via=gnulinux.club) for the design considerations at play re. hacking on `eopkg`.

**Short summary:**
- eopkg doesn't show builddeps (only revdep-rebuild deps)
- eopkg cannot reliably re-order already configured repos
- If multiple repos are configured, eopkg returns the info for a given package from the package it encounters first in its internal PackageDB lookup
- It appears to be non-trivial (approaching intractable?) to fix eopkg to the point where this works correctly
- The least bad (but still hacky) solution appears to be to add an ERROR output (and quit eopkg) if eopkg detects that:
  1. More than one repo is enabled AND
  2. The first repo does not begin with a `file:///` URI.
- The conditions triggering the ERROR output should also be documented in a suitable place in the Packaging HOWTO articles on the Solus Help Center.
- The ERROR output MUST show what a correct, known working `eopkg lr` output looks like.
- The logic that is part of the detection of the ERROR condition SHOULD parse the current repo configuration and then, based on that, generate the correct series of `eopkg` commands that the user can then copy-paste and subsequently execute.

2023-04-24 03:04 UTC, liontiger23 commented
Here are my experiments for several repo configurations (Local and Solus order).
`eopkg` is the current system one, `./eopkg-cli` is the one with the fix from this PR.

1. Prerequisites - setup local repo with just one package `haskell-roman-numerals`:
```
$ ls /var/lib/solbuild/local/
eopkg-index.xml  eopkg-index.xml.sha1sum  eopkg-index.xml.xz  eopkg-index.xml.xz.sha1sum  pandoc-crossref-0.3.4.2-1-1-x86_64.eopkg
$ sudo eopkg index --skip-signing /var/lib/solbuild/local/ --output /var/lib/solbuild/local/eopkg-index.xml
Building index of eopkg files under /var/lib/solbuild/local/

Adding package to index: pandoc-crossref-0.3.4.2-1-1-x86_64.eopkg               
Index file written
$ sudo eopkg update-repo -f
Updating repository: Local
Local repository information is up-to-date.
Updating database at any rate as requested
Package database updated.
Updating repository: Solus
eopkg-index.xml.xz.sha1sum     (40.0  B)100%      0.00 --/- [--:--:--] [complete]
Solus repository information is up-to-date.
Updating database at any rate as requested
eopkg-index.xml.xz             (3.0 MB)100%    181.54 KB/s [00:00:16] [complete]
Package database updated.
```
2. **[Incorrect]** My current configuration (the one described in https://github.com/getsolus/help-center-docs/blob/master/packaging/local-repository/en.md) where Local is first, Solus is second:
```
$ eopkg lr
Local [active]
   /var/lib/solbuild/local/eopkg-index.xml.xz
Solus [active]
   https://cdn.getsol.us/repo/unstable/eopkg-index.xml.xz              
$ eopkg info haskell-roman-numerals
haskell-roman-numerals package is not installed
Package found in Solus repository:
Name                : haskell-roman-numerals, version: 0.5.1.5, release: 1
Summary             : Parsing and pretty printing of Roman numerals
Description         : Parsing and pretty printing of Roman numerals
Licenses            : BSD-3-Clause
Component           : programming.haskell
Dependencies        : glibc gmp haskell-base-unicode-symbols ghc 
Distribution        : Solus, Dist. Release: 1
Architecture        : x86_64, Installed Size: 105.00 KB, Package Size: 18.00 KB
Reverse Dependencies: pandoc-crossref 

$ ./eopkg-cli info haskell-roman-numerals
haskell-roman-numerals package is not installed
Package found in Solus repository:
Name                : haskell-roman-numerals, version: 0.5.1.5, release: 1
Summary             : Parsing and pretty printing of Roman numerals
Description         : Parsing and pretty printing of Roman numerals
Licenses            : BSD-3-Clause
Component           : programming.haskell
Dependencies        : glibc gmp haskell-base-unicode-symbols ghc 
Distribution        : Solus, Dist. Release: 1
Architecture        : x86_64, Installed Size: 105.00 KB, Package Size: 18.00 KB
Reverse Dependencies: haskell-roman-numerals-dbginfo haskell-roman-numerals-devel pandoc-crossref 
```
3. **[Correct]** With just one Solus repo:
```
$ sudo eopkg remove-repo Local
Repo Local removed from system.
$ eopkg lr
Solus [active]
   https://cdn.getsol.us/repo/unstable/eopkg-index.xml.xz
$ eopkg info haskell-roman-numerals
haskell-roman-numerals package is not installed
Package found in Solus repository:
Name                : haskell-roman-numerals, version: 0.5.1.5, release: 1
Summary             : Parsing and pretty printing of Roman numerals
Description         : Parsing and pretty printing of Roman numerals
Licenses            : BSD-3-Clause
Component           : programming.haskell
Dependencies        : glibc gmp haskell-base-unicode-symbols ghc 
Distribution        : Solus, Dist. Release: 1
Architecture        : x86_64, Installed Size: 105.00 KB, Package Size: 18.00 KB
Reverse Dependencies: haskell-roman-numerals-dbginfo haskell-roman-numerals-devel pandoc-crossref 

$ ./eopkg-cli info haskell-roman-numerals
haskell-roman-numerals package is not installed
Package found in Solus repository:
Name                : haskell-roman-numerals, version: 0.5.1.5, release: 1
Summary             : Parsing and pretty printing of Roman numerals
Description         : Parsing and pretty printing of Roman numerals
Licenses            : BSD-3-Clause
Component           : programming.haskell
Dependencies        : glibc gmp haskell-base-unicode-symbols ghc 
Distribution        : Solus, Dist. Release: 1
Architecture        : x86_64, Installed Size: 105.00 KB, Package Size: 18.00 KB
Reverse Dependencies: haskell-roman-numerals-dbginfo haskell-roman-numerals-devel pandoc-crossref 
```
4. **[Correct]** With Local as the second repo:
```
$ sudo eopkg add-repo Local /var/lib/solbuild/local/eopkg-index.xml.xz
Repo Local added to system.
Updating repository: Local
Package database updated.
$ eopkg lr
Solus [active]
   https://cdn.getsol.us/repo/unstable/eopkg-index.xml.xz
Local [active]
   /var/lib/solbuild/local/eopkg-index.xml.xz
$ eopkg info haskell-roman-numerals
haskell-roman-numerals package is not installed
Package found in Solus repository:
Name                : haskell-roman-numerals, version: 0.5.1.5, release: 1
Summary             : Parsing and pretty printing of Roman numerals
Description         : Parsing and pretty printing of Roman numerals
Licenses            : BSD-3-Clause
Component           : programming.haskell
Dependencies        : glibc gmp haskell-base-unicode-symbols ghc 
Distribution        : Solus, Dist. Release: 1
Architecture        : x86_64, Installed Size: 105.00 KB, Package Size: 18.00 KB
Reverse Dependencies: haskell-roman-numerals-dbginfo haskell-roman-numerals-devel pandoc-crossref 

$ ./eopkg-cli info haskell-roman-numerals
haskell-roman-numerals package is not installed
Package found in Solus repository:
Name                : haskell-roman-numerals, version: 0.5.1.5, release: 1
Summary             : Parsing and pretty printing of Roman numerals
Description         : Parsing and pretty printing of Roman numerals
Licenses            : BSD-3-Clause
Component           : programming.haskell
Dependencies        : glibc gmp haskell-base-unicode-symbols ghc 
Distribution        : Solus, Dist. Release: 1
Architecture        : x86_64, Installed Size: 105.00 KB, Package Size: 18.00 KB
Reverse Dependencies: haskell-roman-numerals-dbginfo haskell-roman-numerals-devel pandoc-crossref 
```
5. **[Correct???]** With just Local repo:
```
$ sudo eopkg remove-repo Solus
Repo Solus removed from system.$ eopkg lr
Local [active]
   /var/lib/solbuild/local/eopkg-index.xml.xz
$ eopkg info haskell-roman-numerals
haskell-roman-numerals package is not installed
haskell-roman-numerals package is not found in binary repositories
$ ./eopkg-cli info haskell-roman-numerals
haskell-roman-numerals package is not installed
haskell-roman-numerals package is not found in binary repositories
```
6. **[Incorrect]** Adding Solus repo, bringing us back to the regular setup where Local is first and Solus is second:
```
$ sudo eopkg add-repo Solus https://cdn.getsol.us/repo/unstable/eopkg-index.xml.xz
Repo Solus added to system.
Updating repository: Solus
eopkg-index.xml.xz.sha1sum     (40.0  B)100%      0.00 --/- [--:--:--] [complete]
eopkg-index.xml.xz             (3.0 MB)100%    962.26 KB/s [00:00:02] [complete]
Package database updated.
$ eopkg info haskell-roman-numerals
haskell-roman-numerals package is not installed
Package found in Solus repository:
Name                : haskell-roman-numerals, version: 0.5.1.5, release: 1
Summary             : Parsing and pretty printing of Roman numerals
Description         : Parsing and pretty printing of Roman numerals
Licenses            : BSD-3-Clause
Component           : programming.haskell
Dependencies        : glibc gmp haskell-base-unicode-symbols ghc 
Distribution        : Solus, Dist. Release: 1
Architecture        : x86_64, Installed Size: 105.00 KB, Package Size: 18.00 KB
Reverse Dependencies: pandoc-crossref 

$ ./eopkg-cli info haskell-roman-numerals
haskell-roman-numerals package is not installed
Package found in Solus repository:
Name                : haskell-roman-numerals, version: 0.5.1.5, relea [...]

2023-04-24 03:46 UTC, liontiger23 commented
And updated the code as per @ikeydoherty suggestion to use `isinstance` instead of adding unused `repo` parameter to `installdb` API.

2023-05-22 18:52 UTC, ermo commented
I think this was a worthy effort, but I'm afraid all we've accomplished is to make eopkg lie about the provenance of deps?

When I tested this, I inserted a string describing which repo the revdep info came from and it'd always resolve to Solus rather than the Local repo.

Hence I'm going to recommend that we close this PR, because it it doesn't really do what it says on the tin?

2023-05-23 00:35 UTC, liontiger23 commented
Okay, I agree.

2023-05-23 00:35 UTC, closed without merging